// This file is auto-generated by @hey-api/openapi-ts

export const $Error = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const $Pagination = {
    type: 'object',
    properties: {
        count: {
            type: 'integer'
        },
        offset: {
            type: 'integer'
        },
        limit: {
            type: 'integer'
        }
    }
} as const;

export const $ProductCreate = {
    type: 'object',
    required: ['name'],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const $ProductUpdate = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            'x-nullable': true
        },
        description: {
            type: 'string',
            'x-nullable': true
        }
    }
} as const;

export const $ProductResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const $ProductResponseArray = {
    allOf: [
        {
            '$ref': '#/definitions/Pagination'
        },
        {
            type: 'object',
            properties: {
                products: {
                    type: 'array',
                    items: {
                        '$ref': '#/definitions/ProductResponse'
                    }
                }
            }
        }
    ]
} as const;

export const $CartCreate = {
    type: 'object',
    required: ['productIds'],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        productIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid4'
            }
        }
    }
} as const;

export const $CartUpdate = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            'x-nullable': true
        },
        description: {
            type: 'string',
            'x-nullable': true
        },
        productIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid4'
            }
        }
    }
} as const;

export const $CartResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid4'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        products: {
            type: 'array',
            items: {
                '$ref': '#/definitions/ProductResponse'
            }
        }
    }
} as const;

export const $CartResponseArray = {
    allOf: [
        {
            '$ref': '#/definitions/Pagination'
        },
        {
            type: 'object',
            properties: {
                carts: {
                    type: 'array',
                    items: {
                        '$ref': '#/definitions/CartResponse'
                    }
                }
            }
        }
    ]
} as const;

export const $PaymentCreate = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        }
    }
} as const;

export const $PaymentUpdate = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            'x-nullable': true
        }
    }
} as const;

export const $PaymentResponse = {
    type: 'object',
    required: ['id', 'status'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid4'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $PaymentResponseArray = {
    allOf: [
        {
            '$ref': '#/definitions/Pagination'
        },
        {
            type: 'object',
            properties: {
                payments: {
                    type: 'array',
                    items: {
                        '$ref': '#/definitions/PaymentResponse'
                    }
                }
            }
        }
    ]
} as const;