// This file is auto-generated by @hey-api/openapi-ts

export type Error = {
    message?: string;
};

export type Pagination = {
    count?: number;
    offset?: number;
    limit?: number;
};

export type ProductCreate = {
    name: string;
    description?: string;
};

export type ProductUpdate = {
    name?: string | null;
    description?: string | null;
};

export type ProductResponse = {
    id?: string;
    name?: string;
    description?: string;
};

export type ProductResponseArray = Pagination & {
    products?: Array<ProductResponse>;
};

export type CartCreate = {
    name?: string;
    description?: string;
    productIds: Array<(string)>;
};

export type CartUpdate = {
    name?: string | null;
    description?: string | null;
    productIds?: Array<(string)>;
};

export type CartResponse = {
    id?: string;
    name?: string;
    description?: string;
    products?: Array<ProductResponse>;
};

export type CartResponseArray = Pagination & {
    carts?: Array<CartResponse>;
};

export type PaymentCreate = {
    status?: string;
};

export type PaymentUpdate = {
    status?: string | null;
};

export type PaymentResponse = {
    id: string;
    status: string;
};

export type PaymentResponseArray = Pagination & {
    payments?: Array<PaymentResponse>;
};

export type CreateProductData = {
    body: ProductCreate;
};

export type CreateProductResponse = ProductResponse;

export type GetProductsData = {
    limit?: number;
    offset?: number;
};

export type GetProductsResponse = ProductResponseArray;

export type GetProductByIdData = {
    /**
     * Product ID
     */
    productId: string;
};

export type GetProductByIdResponse = ProductResponse;

export type PatchProductsByProductIdData = {
    body: ProductUpdate;
    /**
     * Product ID
     */
    productId: string;
};

export type PatchProductsByProductIdResponse = ProductResponse;

export type DeleteProductByIdData = {
    /**
     * Product ID
     */
    productId: string;
};

export type DeleteProductByIdResponse = void;

export type CreateCartData = {
    body: CartCreate;
};

export type CreateCartResponse = CartResponse;

export type GetCartsData = {
    limit?: number;
    offset?: number;
};

export type GetCartsResponse = CartResponseArray;

export type GetCartByIdData = {
    /**
     * Product ID
     */
    cartId: string;
};

export type GetCartByIdResponse = CartResponse;

export type PatchCartsByCartIdData = {
    body: CartUpdate;
    /**
     * Cart ID
     */
    cartId: string;
};

export type PatchCartsByCartIdResponse = CartResponse;

export type DeleteCartByIdData = {
    /**
     * Cart ID
     */
    cartId: string;
};

export type DeleteCartByIdResponse = void;

export type CreatePaymentData = {
    body: PaymentCreate;
};

export type CreatePaymentResponse = PaymentResponse;

export type GetPaymentsData = {
    limit?: number;
    offset?: number;
};

export type GetPaymentsResponse = PaymentResponseArray;

export type GetPaymentByIdData = {
    /**
     * Payment ID
     */
    paymentId: string;
};

export type GetPaymentByIdResponse = PaymentResponse;

export type UpdatePaymentByIdData = {
    body: PaymentUpdate;
    /**
     * Payment ID
     */
    paymentId: string;
};

export type UpdatePaymentByIdResponse = PaymentResponse;

export type DeletePaymentByIdData = {
    /**
     * Payment ID
     */
    paymentId: string;
};

export type DeletePaymentByIdResponse = void;

export type $OpenApiTs = {
    '/products': {
        post: {
            req: {
                body: ProductCreate;
            };
            res: {
                201: ProductResponse;
            };
        };
        get: {
            req: {
                limit?: number;
                offset?: number;
            };
            res: {
                200: ProductResponseArray;
            };
        };
    };
    '/products/{productId}': {
        get: {
            req: {
                /**
                 * Product ID
                 */
                productId: string;
            };
            res: {
                200: ProductResponse;
            };
        };
        patch: {
            req: {
                body: ProductUpdate;
                /**
                 * Product ID
                 */
                productId: string;
            };
            res: {
                200: ProductResponse;
            };
        };
        delete: {
            req: {
                /**
                 * Product ID
                 */
                productId: string;
            };
            res: {
                204: void;
            };
        };
    };
    '/carts': {
        post: {
            req: {
                body: CartCreate;
            };
            res: {
                201: CartResponse;
            };
        };
        get: {
            req: {
                limit?: number;
                offset?: number;
            };
            res: {
                200: CartResponseArray;
            };
        };
    };
    '/carts/{cartId}': {
        get: {
            req: {
                /**
                 * Product ID
                 */
                cartId: string;
            };
            res: {
                200: CartResponse;
            };
        };
        patch: {
            req: {
                body: CartUpdate;
                /**
                 * Cart ID
                 */
                cartId: string;
            };
            res: {
                200: CartResponse;
            };
        };
        delete: {
            req: {
                /**
                 * Cart ID
                 */
                cartId: string;
            };
            res: {
                204: void;
            };
        };
    };
    '/payments': {
        post: {
            req: {
                body: PaymentCreate;
            };
            res: {
                201: PaymentResponse;
            };
        };
        get: {
            req: {
                limit?: number;
                offset?: number;
            };
            res: {
                200: PaymentResponseArray;
            };
        };
    };
    '/payments/{paymentId}': {
        get: {
            req: {
                /**
                 * Payment ID
                 */
                paymentId: string;
            };
            res: {
                200: PaymentResponse;
            };
        };
        patch: {
            req: {
                body: PaymentUpdate;
                /**
                 * Payment ID
                 */
                paymentId: string;
            };
            res: {
                200: PaymentResponse;
            };
        };
        delete: {
            req: {
                /**
                 * Payment ID
                 */
                paymentId: string;
            };
            res: {
                204: void;
            };
        };
    };
};